title: 4rm4n1's Write-ups
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "4rm4n1"
  email: "armandorenuncio@proton.me"
  url: "www.linkedin.com/in/armando-renuncio-741408224"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
owner : "4rm4n1"
year : "2026"
